package it.unirc.pwm.ht;
// Generated 12 dic 2023, 16:08:36 by Hibernate Tools 6.1.3.Final

import java.util.HashSet;
import java.util.Set;


/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCliente;
	private String email;
	private String password;
	private String nome;
	private String cognome;
	private Clienteprime clienteprime;
	private Set<Carrello> carrellos = new HashSet<Carrello>(0);
//	private Set<IndirizzoSpedizione> indirizzospediziones = new HashSet<IndirizzoSpedizione>(0);
//	private Set<CartaCredito> cartacreditos = new HashSet<CartaCredito>(0);

	public Cliente() {
	}
	public Cliente(int idCliente) {
		super();
		this.idCliente = idCliente;
	}

	public Cliente(String email, String password, String nome, String cognome) {
		this.email = email;
		this.password = password;
		this.nome = nome;
		this.cognome = cognome;
	}

	public Cliente(String email, String password, String nome, String cognome, 
			Clienteprime clienteprime, Set<Carrello> carrellos) {
		this.email = email;
		this.password = password;
		this.nome = nome;
		this.cognome = cognome;
		this.clienteprime = clienteprime;
		this.carrellos = carrellos;
//		this.indirizzospediziones = indirizzospediziones;
//		this.cartacreditos = cartacreditos;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}


	public Clienteprime getClienteprime() {
		return this.clienteprime;
	}

	public void setClienteprime(Clienteprime clienteprime) {
		this.clienteprime = clienteprime;
	}

	public Set<Carrello> getCarrellos() {
		return this.carrellos;
	}

	public void setCarrellos(Set<Carrello> carrellos) {
		this.carrellos = carrellos;
	}

//	public Set<Indirizzospedizione> getIndirizzospediziones() {
//		return this.indirizzospediziones;
//	}
//
//	public void setIndirizzospediziones(Set<Indirizzospedizione> indirizzospediziones) {
//		this.indirizzospediziones = indirizzospediziones;
//	}
//
//	public Set<CartaCredito> getCartacreditos() {
//		return this.cartacreditos;
//	}
//
//	public void setCartacreditos(Set<CartaCredito> cartacreditos) {
//		this.cartacreditos = cartacreditos;
//	}
	@Override
	public String toString() {
		return "Cliente [idCliente=" + idCliente + ", email=" + email + ", password=" + password + ", nome=" + nome
				+ ", cognome=" + cognome + "]";
	}

	

}
